[build]
  publish = "public"
  command = "mpn ci || mpn i"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  
[functions."*"]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
